input.onButtonPressed(Button.A, function () {
    music.setBuiltInSpeakerEnabled(true)
    music.startMelody(music.builtInMelody(Melodies.Dadadadum), MelodyOptions.Once)
    music.playMelody("C - C - E - - G ", 500)
    music.rest(music.beat(BeatFraction.Breve))
    music.playMelody("D D - D - E - - ", 500)
    music.playMelody("D - - C - - - E ", 500)
    music.playMelody("- - G - - - C C ", 500)
    music.playMelody("- - - E E - - E ", 500)
    music.playMelody("- D - - C - - - ", 500)
    music.playMelody("E - - G - - - D ", 500)
    music.playMelody("- D - - E - - D ", 500)
    music.playMelody("- - C - - E - - ", 500)
    music.playMelody("G - - C C - - - ", 500)
    music.playMelody("E E - - E - D - ", 500)
    music.playMelody("- - C - - E - - ", 500)
    music.playMelody("G - - - D - - - ", 500)
    music.playMelody("D - E - - D - - ", 500)
    music.playMelody("C - - E - - G - ", 500)
    music.playMelody("- - D - - D - E ", 500)
    music.playMelody("- - - D - - C - ", 500)
    music.playMelody("- - E - - G - - ", 500)
    music.playMelody("- D - - D - E - ", 500)
    music.playMelody("- D - C C C - - ", 500)
})
input.onButtonPressed(Button.B, function () {
    music.playMelody("E - - D - - - D ", 500)
    music.playMelody("- E - C - - - - ", 500)
    music.playMelody("- - C - - C - - ", 500)
    music.playMelody("E E D D D D - D ", 500)
    music.playMelody("E C - - - C - C ", 500)
    music.playMelody("- E E E E - G - ", 500)
    music.playMelody("- E - D - E - C ", 500)
    music.playMelody("C C C - E E - E ", 500)
    music.playMelody("E - G - E E - D ", 500)
})
